import { IMenuOutput } from "@/shared/menu/IMenu";
import { ITaskCategoryDto } from "@/domain/pipelinetemplates/pipelinetemplate-dto";
import { StepTypeEnum } from "@/domain/applicationpipelines/applicationpipeline-enum";

export const menuList: IMenuOutput[] = [
  {
    id: "1000",
    name: "首页",
    path: "/home",
    component: "pages/home/home",
    tabs: [],
    buttonClick: "",
    buttons: [],
    parentId: "000",
    icon: "",
    parentNumber: "",
    microName: "",
    componentName: "home",
    sort: 0,
    isShow: true,
    type: 0,
    children: [],
  },
  {
    id: "1001",
    name: "应用中心",
    path: "/application",
    component: "pages/application-page/index",
    tabs: [],
    buttonClick: "",
    buttons: [],
    parentId: "000",
    icon: "<DesktopOutlined/>",
    parentNumber: "",
    microName: "",
    componentName: "test-page",
    sort: 0,
    isShow: true,
    type: 0,
    children: [
      {
        id: "1001-1",
        name: "应用列表",
        path: "/application/list",
        component: "pages/application-page/index",
        tabs: [],
        buttonClick: "",
        buttons: [],
        parentId: "000",
        icon: "",
        parentNumber: "",
        microName: "",
        componentName: "application-page",
        sort: 0,
        isShow: true,
        type: 0,
        children: [],
      },
      {
        id: "1001-2",
        name: "应用仪表盘",
        path: "/application/dashboard",
        component: "pages/application-page/application-dashboard",
        tabs: [],
        buttonClick: "",
        buttons: [],
        parentId: "000",
        icon: "",
        parentNumber: "",
        microName: "",
        componentName: "menu-page",
        sort: 0,
        isShow: false,
        type: 0,
        children: [],
      },
      {
        id: "1001-3",
        name: "配置中心",
        path: "/application/configcenter",
        component: "pages/config/indexnew",
        tabs: [],
        buttonClick: "",
        buttons: [],
        parentId: "000",
        icon: "",
        parentNumber: "",
        microName: "",
        componentName: "menu-page",
        sort: 0,
        isShow: false,
        type: 0,
        children: [],
      },
      {
        id: "1001-5",
        name: "应用流水线配置",
        path: "/application/pipeline/flow/config",
        component: "pages/application-pipeline-page/pipeline-flow-config",
        tabs: [],
        buttonClick: "",
        buttons: [],
        parentId: "000",
        icon: "",
        parentNumber: "",
        microName: "",
        componentName: "menu-page",
        sort: 0,
        isShow: false,
        type: 0,
        children: [],
      },
      {
        id: "1001-6",
        name: "WorkLoad配置",
        path: "/tks/kubernetes/workload/config",
        component: "pages/wke/kubernetes/workload-page/workload-config",
        tabs: [],
        buttonClick: "",
        buttons: [],
        parentId: "000",
        icon: "",
        parentNumber: "",
        microName: "",
        componentName: "menu-page",
        sort: 0,
        isShow: false,
        type: 0,
        children: [],
      },
    ],
  },
  {
    id: "1004",
    name: "基础设施",
    path: "/componentintegration",
    component: "pages/componentintegration-page/index",
    tabs: [],
    buttonClick: "",
    buttons: [],
    parentId: "000",
    icon: "<DesktopOutlined/>",
    parentNumber: "",
    microName: "",
    componentName: "test-page",
    sort: 0,
    isShow: true,
    type: 0,
    children: [
      {
        id: "1004-1",
        name: "组件集成配置",
        path: "/componentintegration/config",
        component: "pages/componentintegration-page/index",
        tabs: [],
        buttonClick: "",
        buttons: [],
        parentId: "000",
        icon: "",
        parentNumber: "",
        microName: "",
        componentName: "dove-log",
        sort: 0,
        isShow: true,
        type: 0,
        children: [],
      },
      {
        id: "1004-2",
        name: "镜像管理",
        path: "/buildimage/manage",
        component: "pages/buildimage-page/index",
        tabs: [],
        buttonClick: "",
        buttons: [],
        parentId: "000",
        icon: "",
        parentNumber: "",
        microName: "",
        componentName: "dove-log",
        sort: 0,
        isShow: true,
        type: 0,
        children: [],
      },
      {
        id: "1004-3",
        name: "SideCar组件",
        path: "/initcontainer/InitContainerConfigurationPage",
        component: "pages/initcontainer-page/index",
        tabs: [],
        buttonClick: "",
        buttons: [],
        parentId: "000",
        icon: "",
        parentNumber: "",
        microName: "",
        componentName: "dove-log",
        sort: 0,
        isShow: true,
        type: 0,
        children: [],
      },
      {
        id: "1004-4",
        name: "环境管理",
        path: "/Environment/EnvironmentPage",
        component: "pages/environment/index",
        tabs: [],
        buttonClick: "",
        buttons: [],
        parentId: "000",
        icon: "",
        parentNumber: "",
        microName: "",
        componentName: "environment",
        sort: 0,
        isShow: true,
        type: 0,
        children: [],
      }
    ],
  },
  {
    id: "1005",
    name: "TKS",
    path: "/tks/dashboard",
    component: "pages/wke/kubernetes/kubernetes-dashboard",
    tabs: [],
    buttonClick: "",
    buttons: [],
    parentId: "000",
    icon: "<DesktopOutlined/>",
    parentNumber: "",
    microName: "",
    componentName: "wke-dashboard-page",
    sort: 0,
    isShow: true,
    type: 0,
    children: [
      {
        id: "1005-1",
        name: "Cluster OverView",
        path: "/tks/kubernetes/dashboard",
        component: "pages/wke/kubernetes/kubernetes-dashboard",
        tabs: [],
        buttonClick: "",
        buttons: [],
        parentId: "000",
        icon: "",
        parentNumber: "",
        microName: "",
        componentName: "tks-cluster-dashboard",
        sort: 0,
        isShow: true,
        type: 0,
        children: [],
      },
      {
        id: "1005-2",
        name: "集群管理",
        path: "/tks/kubernetes/cluster",
        component: "pages/wke/kubernetes/cluster-page/index",
        tabs: [],
        buttonClick: "",
        buttons: [],
        parentId: "000",
        icon: "",
        parentNumber: "",
        microName: "",
        componentName: "wke-cluster",
        sort: 0,
        isShow: true,
        type: 0,
        children: [],
      },
      {
        id: "1005-3",
        name: "NameSpace",
        path: "/tks/kubernetes/namespace",
        component: "pages/wke/kubernetes/namespace-page/index",
        tabs: [],
        buttonClick: "",
        buttons: [],
        parentId: "000",
        icon: "",
        parentNumber: "",
        microName: "",
        componentName: "wke-namespace",
        sort: 0,
        isShow: true,
        type: 0,
        children: [],
      }],
  },
  {
    id: "1006",
    name: "模板管理",
    path: "/template",
    component: "pages/templates/pipeline-template-page",
    tabs: [],
    buttonClick: "",
    buttons: [],
    parentId: "000",
    icon: "<DesktopOutlined/>",
    parentNumber: "",
    microName: "",
    componentName: "wke-dashboard-page",
    sort: 0,
    isShow: true,
    type: 0,
    children: [
      {
        id: "1006-1",
        name: "CI流水线模板",
        path: "/pipeline/templates",
        component: "pages/templates/pipeline-template-page/index",
        tabs: [],
        buttonClick: "",
        buttons: [],
        parentId: "000",
        icon: "",
        parentNumber: "",
        microName: "",
        componentName: "jenkins-config-page",
        sort: 0,
        isShow: true,
        type: 0,
        children: [],
      },
      {
        id: "1006-2",
        name: "JenkinsConfig",
        path: "/ci/pipeline/templates/edit",
        component: "pages/templates/pipeline-template-page/operation",
        tabs: [],
        buttonClick: "",
        buttons: [],
        parentId: "000",
        icon: "",
        parentNumber: "",
        microName: "",
        componentName: "templates-jenkins-config-page",
        sort: 0,
        isShow: false,
        type: 0,
        children: [],
      }
    ],
  },
]


